[build]
  base = "frontend"  # Establece la carpeta base donde se encuentra tu código fuente
  command = "npm run build"  # Comando para construir el proyecto
  publish = "FronEnd\dist"  # Directorio de salida de tu build

[[redirects]]
  from = "/api/*"
  to = "http://localhost:8444"
  status = 200
  force = true
